import pandas as pd
import json
from pathlib import Path

class NexusMapper:
    def __init__(self):
        # Initialize empty lists for the graph structure
        self.nodes = []
        self.edges = []
        # Use a set to track unique IDs and prevent duplicate nodes
        self.node_set = set() 

    def add_node(self, node_id, node_type):
        """Helper to add unique entities to the graph."""
        if pd.notna(node_id) and node_id not in self.node_set:
            self.nodes.append({
                "id": str(node_id), 
                "type": node_type
            })
            self.node_set.add(node_id)

    def add_edge(self, source, target, relation, timestamp=None, channel=None):
        """Helper to map relationships between entities."""
        if pd.notna(source) and pd.notna(target):
            edge = {
                "source": str(source),
                "target": str(target),
                "relation": relation
            }
            # Attach temporal and channel data for the GNN Brain
            if timestamp:
                edge["timestamp"] = str(timestamp)
            if channel:
                edge["channel"] = str(channel)
                
            self.edges.append(edge)

    def map_log_to_nexus(self, df):
        """
        The core engine: Converts flat bank logs into a Heterogeneous Multigraph.
        """
        print(f"[*] Ingesting {len(df)} cross-channel log entries...")
        
        for _, row in df.iterrows():
            # 1. Extract Raw Entities
            acc_id = row.get('account_id')
            device_id = row.get('device_id') # IMEI, UUID, or Browser Fingerprint
            ip_addr = row.get('ip_address')
            
            # 2. Register Nodes (Hardware-Entity Resolution)
            self.add_node(acc_id, "account")
            self.add_node(device_id, "device")
            self.add_node(ip_addr, "ip")
            
            # 3. Create Edges (The Relationships)
            
            # Link Account to Device (Catches multiple accounts on one IMEI)
            self.add_edge(
                source=acc_id, 
                target=device_id, 
                relation="uses_device", 
                timestamp=row.get('timestamp'),
                channel=row.get('channel') # e.g., Mobile App, Web, ATM
            )
            
            # Link Account to IP (Catches IP-Subnet Scam Hubs)
            self.add_edge(
                source=acc_id,
                target=ip_addr,
                relation="accesses_from_ip",
                timestamp=row.get('timestamp')
            )
        
        print(f"[*] Graph built: {len(self.nodes)} Nodes, {len(self.edges)} Edges.")
        return {"nodes": self.nodes, "edges": self.edges}

    def export_to_json(self, output_path):
        """Saves the graph for Member 1's PyTorch Geometric ingestion."""
        with open(output_path, 'w') as f:
            json.dump({"nodes": self.nodes, "edges": self.edges}, f, indent=4)
        print(f"[*] Nexus Graph exported successfully to {output_path}")

# ==========================================
# TEST EXECUTION (Reads the CSV from generator.py)
# ==========================================
if __name__ == "__main__":
    # 1. Define paths
    current_dir = Path(__file__).parent
    csv_file = current_dir / 'raw_bank_logs.csv'
    output_json = current_dir / 'nexus_graph_output.json'
    
    # 2. Check if the CSV exists (generated by generator.py)
    if not csv_file.exists():
        print(f"[!] Error: {csv_file} not found. Run generator.py first!")
    else:
        # 3. Read the CSV
        print(f"[*] Reading raw logs from {csv_file.name}...")
        df = pd.read_csv(csv_file)
        
        # 4. Run the Mapper
        mapper = NexusMapper()
        graph_data = mapper.map_log_to_nexus(df)
        
        # 5. Export the JSON
        mapper.export_to_json(output_json)